/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Admin;

import Business.ConfigureASystem;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import com.google.zxing.WriterException;
import javax.swing.JPanel;
import helper.Helper;
import static helper.Helper.createQRCode;
import static helper.Helper.getGoogleAuthenticatorBarCode;
import static helper.Helper.getTOTPCode;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.IOException;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import userinterface.UserRole.UserSignUp;
import userinterface.UserRole.UserWorkAreaJPanel;

/**
 *
 * @author ashwin
 */
public class AdminSignup extends javax.swing.JPanel {

    JPanel container; 
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    
    public AdminSignup() {
        initComponents();
    }

    public AdminSignup(JPanel container, EcoSystem system) {
        this();
        this.container = container;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        adminSignUpBtn = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 700));
        setMinimumSize(new java.awt.Dimension(1400, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1400, 700));

        username.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Admin Username");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Password");

        jPanel3.setBackground(new java.awt.Color(181, 181, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Admin Login");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(746, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        adminSignUpBtn.setBackground(new java.awt.Color(255, 255, 255));
        adminSignUpBtn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        adminSignUpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Signup.png"))); // NOI18N
        adminSignUpBtn.setText("Sign Up");
        adminSignUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminSignUpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminSignUpBtnMouseExited(evt);
            }
        });
        adminSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSignUpBtnActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminSignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(adminSignUpBtn)
                .addContainerGap(371, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSignUpBtnActionPerformed
        String user = username.getText();
        String pass = String.valueOf(txtPassword.getPassword());
        
        if(user.isEmpty() || pass.isEmpty()){
            JOptionPane.showMessageDialog(null, "Fields cannot be empty. Please enter all fields");
            return;
        }
        
        Boolean alreayExists = Helper.doesUsernameExist(system, user);
        if(alreayExists == true){
            JOptionPane.showMessageDialog(null, "Username already exists");
            return;
        }
        
        if(user.length() > 20 ){
            JOptionPane.showMessageDialog(null, "Username cannot exceed 20 characters");
            return;
        }
        
        Boolean passwordStrength = Helper.isPasswordStrong(pass);
        System.out.println(pass);
        if(passwordStrength == false){
            JOptionPane.showMessageDialog(null, "Enter strong password");
            return;
        }
        
       
        String secretKey = Helper.generateSecretKey();
         
        Employee employee = system.getEmployeeDirectory().createEmployee(user);
        UserAccount ua = system.getUserAccountDirectory().createUserAccount(user, pass, employee, new SystemAdminRole(), secretKey);
        
        String barCodeUrl = getGoogleAuthenticatorBarCode(secretKey, user, "NineNine");
        try {
            createQRCode(barCodeUrl, System.getProperty("user.dir") + "\\Images\\QRCode.png", 400, 400);
            dB4OUtil.storeSystem(system);
            CardLayout layout = (CardLayout)container.getLayout();
            container.add(new BarCodeJPanel(container, system));
            layout.next(container);
        
        } catch (WriterException ex) {
            Logger.getLogger(AdminSignup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AdminSignup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adminSignUpBtnActionPerformed
  public void setColor(JButton p){
        p.setBackground(new Color(102,102,255));
    }
    public void resetColor(JButton p1){
        p1.setBackground(new Color(255,255,255));
        
    }
    private void adminSignUpBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSignUpBtnMouseEntered
        // TODO add your handling code here:
        setColor(adminSignUpBtn);
    }//GEN-LAST:event_adminSignUpBtnMouseEntered

    private void adminSignUpBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSignUpBtnMouseExited
        // TODO add your handling code here:
        resetColor(adminSignUpBtn);
    }//GEN-LAST:event_adminSignUpBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminSignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
