/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnforcementRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EnforcementOrganization;
import Business.Organization.GoverningBodyOrganization;
import Business.Organization.Organization;
import Business.UserAccount.DoctorAccount;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PrescriptionRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashwin
 */
public class EnforcementOrgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnforcementOrgJPanel
     */
    private JPanel userProcessContainer;
    private EnforcementOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    
    public EnforcementOrgJPanel(JPanel userProcessContainer, UserAccount account, EnforcementOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        doctorLicenseJTable.setFillsViewportHeight(true);
        populateTable(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalysis = new javax.swing.JButton();
        btnAnalysis1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorLicenseJTable = new javax.swing.JTable();
        btnRevoke = new javax.swing.JButton();
        txtDoctor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1225, 700));
        setMinimumSize(new java.awt.Dimension(1225, 700));
        setPreferredSize(new java.awt.Dimension(1225, 700));

        btnAnalysis.setBackground(new java.awt.Color(255, 255, 255));
        btnAnalysis.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnAnalysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye.png"))); // NOI18N
        btnAnalysis.setText("View doctors by licence");
        btnAnalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnalysisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnalysisMouseExited(evt);
            }
        });
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });

        btnAnalysis1.setBackground(new java.awt.Color(255, 255, 255));
        btnAnalysis1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnAnalysis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye.png"))); // NOI18N
        btnAnalysis1.setText("View Presciption Count by doctor");
        btnAnalysis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnalysis1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnalysis1MouseExited(evt);
            }
        });
        btnAnalysis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysis1ActionPerformed(evt);
            }
        });

        doctorLicenseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                                        Doctor Name", "Licence"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorLicenseJTable.setGridColor(new java.awt.Color(255, 255, 255));
        doctorLicenseJTable.setRowHeight(22);
        jScrollPane1.setViewportView(doctorLicenseJTable);

        btnRevoke.setBackground(new java.awt.Color(255, 255, 255));
        btnRevoke.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnRevoke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wrong.png"))); // NOI18N
        btnRevoke.setText("Revoke Licence");
        btnRevoke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevokeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevokeMouseExited(evt);
            }
        });
        btnRevoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevokeActionPerformed(evt);
            }
        });

        txtDoctor.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDoctorKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Seach Doctor by name :");

        jPanel3.setBackground(new java.awt.Color(181, 181, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Control Panel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRevoke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnalysis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnalysis1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(410, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnAnalysis1)
                .addGap(58, 58, 58)
                .addComponent(btnAnalysis)
                .addGap(68, 68, 68)
                .addComponent(btnRevoke)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:

        GoverningBodyAnalysis chart = new GoverningBodyAnalysis("Pie Chart", "Doctors With licence", system);
        chart.pack();
        chart.setVisible(true);
    }//GEN-LAST:event_btnAnalysisActionPerformed

    private void btnAnalysis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysis1ActionPerformed
        // TODO add your handling code here:
        DoctorByPrescriptionAnalysis drAnalysis = new DoctorByPrescriptionAnalysis(system);
    }//GEN-LAST:event_btnAnalysis1ActionPerformed

    private void btnRevokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevokeActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctorLicenseJTable.getSelectedRow();
        if(selectedRow >= 0){
            DoctorAccount dr = (DoctorAccount)doctorLicenseJTable.getValueAt(selectedRow, 0);
            System.out.println(dr);
            dr.setLicense(false);
            dB4OUtil.storeSystem(system);
            populateTable(null);
        }
    }//GEN-LAST:event_btnRevokeActionPerformed

    private void txtDoctorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoctorKeyPressed
        String setSearch = txtDoctor.getText();
        populateTable(setSearch);
        setSearch = null;
    }//GEN-LAST:event_txtDoctorKeyPressed

    private void btnAnalysisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalysisMouseEntered
        // TODO add your handling code here:
        setColor(btnAnalysis);
    }//GEN-LAST:event_btnAnalysisMouseEntered

    private void btnAnalysisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalysisMouseExited
        // TODO add your handling code here:
        resetColor(btnAnalysis);
    }//GEN-LAST:event_btnAnalysisMouseExited

    private void btnAnalysis1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalysis1MouseEntered
        // TODO add your handling code here:
        setColor(btnAnalysis1);
    }//GEN-LAST:event_btnAnalysis1MouseEntered

    private void btnAnalysis1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalysis1MouseExited
        // TODO add your handling code here:
        resetColor(btnAnalysis1);
    }//GEN-LAST:event_btnAnalysis1MouseExited

    private void btnRevokeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevokeMouseEntered
        // TODO add your handling code here:
        setColor(btnRevoke);
    }//GEN-LAST:event_btnRevokeMouseEntered

    private void btnRevokeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevokeMouseExited
        // TODO add your handling code here:
        resetColor(btnRevoke);
    }//GEN-LAST:event_btnRevokeMouseExited
public void setColor(JButton p){
        p.setBackground(new Color(102,102,255));
    }
    public void resetColor(JButton p1){
        p1.setBackground(new Color(255,255,255));
        
    }
    private void populateTable(String setSearch){
        DefaultTableModel dtm = (DefaultTableModel) doctorLicenseJTable.getModel();
        dtm.setRowCount(0);
        for(Network network: system.getNetworkList()){
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise.getEnterpriseType() == Enterprise.EnterpriseType.GoverningBody) {
                    for(Organization organization: enterprise.getOrganizationDirectory().getOrganizationList()) {
                        for(UserAccount acc : organization.getUserAccountDirectory().getUserAccountList()){
                            if(acc.getRole().toString().equals("Business.Role.DoctorRole")){
                                DoctorAccount dr = (DoctorAccount) acc;
                                if(setSearch != null){
                                    if(dr.toString().contains(setSearch)){
                                        Object row[] = new Object[2];
                                        row[0] = dr;
                                        row[1] = dr.isLicense();
                                        dtm.addRow(row);
                                    }
                                }
                                else{
                                    Object row[] = new Object[2];
                                    row[0] = dr;
                                    row[1] = dr.isLicense();
                                    dtm.addRow(row);
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnAnalysis1;
    private javax.swing.JButton btnRevoke;
    private javax.swing.JTable doctorLicenseJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDoctor;
    // End of variables declaration//GEN-END:variables
}
