/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.DoctorRole;
import Business.Organization.DoctorOrganization;
import static Business.Organization.Organization.GoverningBodyEnterpriseOrganizationType.Doctor;
import Business.Organization.Organization;
import Business.UserAccount.DoctorAccount;
import Business.UserAccount.StoreAccount;
import Business.UserAccount.UserAccount;
import Business.UserAccount.DoctorAccount;
import Business.WorkQueue.PrescriptionRequest;
import Business.WorkQueue.WorkRequest;
import helper.Prescription;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import helper.Helper;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ashwin
 */
public class UserWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DoctorOrganization dro;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public UserWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system){
        initComponents();
        this.dro = dro;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        userWorkRequestJTable.setFillsViewportHeight(true);
        workRequestJTable.setFillsViewportHeight(true);
        populateTable();  
        populateStoreTable();
        PatientName.setText(userAccount.getEmployee().getName());
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(userAccount.getViewUser()));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image userImg = img.getScaledInstance(150, 150,Image.SCALE_SMOOTH);
        //ImageIcon userImg = new ImageIcon(userAccount.getViewUser());
        ImageIcon imageIcon = new ImageIcon(userImg);
        lblUser.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetPrescription = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        valueLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userWorkRequestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PatientName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        managePrescriptionsBtn = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewRequestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1225, 700));
        setMinimumSize(new java.awt.Dimension(1225, 700));
        setPreferredSize(new java.awt.Dimension(1225, 700));

        btnGetPrescription.setBackground(new java.awt.Color(255, 255, 255));
        btnGetPrescription.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnGetPrescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GetPrescription.png"))); // NOI18N
        btnGetPrescription.setText("Get Prescription");
        btnGetPrescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGetPrescriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGetPrescriptionMouseExited(evt);
            }
        });
        btnGetPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPrescriptionActionPerformed(evt);
            }
        });

        refreshTestJButton.setBackground(new java.awt.Color(255, 255, 255));
        refreshTestJButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        refreshTestJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshTestJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshTestJButtonMouseExited(evt);
            }
        });
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        valueLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        valueLabel1.setText("Hope you are doing well today!");

        enterpriseLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        enterpriseLabel.setText("Hello ");

        jPanel1.setBackground(new java.awt.Color(181, 181, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        userWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor", "Is Licensed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userWorkRequestJTable.setGridColor(new java.awt.Color(255, 255, 255));
        userWorkRequestJTable.setRowHeight(22);
        jScrollPane1.setViewportView(userWorkRequestJTable);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Please choose the doctor you wish to get prescription from:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PatientName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(181, 181, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Store Address", "Status", "Request Date and Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setGridColor(new java.awt.Color(255, 255, 255));
        workRequestJTable.setRowHeight(22);
        jScrollPane2.setViewportView(workRequestJTable);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("All requests so far:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        managePrescriptionsBtn.setBackground(new java.awt.Color(255, 255, 255));
        managePrescriptionsBtn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        managePrescriptionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Prescription.png"))); // NOI18N
        managePrescriptionsBtn.setText("Manage Prescriptions");
        managePrescriptionsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managePrescriptionsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managePrescriptionsBtnMouseExited(evt);
            }
        });
        managePrescriptionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePrescriptionsBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(181, 181, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Workspace");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewRequestBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewRequestBtn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        viewRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye.png"))); // NOI18N
        viewRequestBtn.setText("View Request");
        viewRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRequestBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRequestBtnMouseExited(evt);
            }
        });
        viewRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(refreshTestJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGetPrescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePrescriptionsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewRequestBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(enterpriseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PatientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(876, 876, 876))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGetPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(managePrescriptionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        populateTable();  
        populateStoreTable(); 
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void btnGetPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPrescriptionActionPerformed
        // TODO add your handling code here:
        int selectedRow = userWorkRequestJTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            DoctorAccount drUserAccount = (DoctorAccount) userWorkRequestJTable.getValueAt(selectedRow, 0);
            Prescription prescription = new Prescription();
            prescription.setDoctor(drUserAccount);
            prescription.setPatient(userAccount);            
            userAccount.addPrescription(prescription);
  
            
            dB4OUtil.storeSystem(system);
            
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            userProcessContainer.add(new PrescriptionJPanel(userProcessContainer, userAccount, system));
            layout.next(userProcessContainer);
        } 
        else {
            JOptionPane.showMessageDialog(null, "Please select a Doctor.");
        }
        
    }
    private void populateTable() {
       DefaultTableModel dtm = (DefaultTableModel) userWorkRequestJTable.getModel();
       dtm.setRowCount(0);

        for(Network network: system.getNetworkList()){
            if(network.getName().equals(userAccount.getNetwork().getName())) {
                for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()) {
                    if(enterprise.getEnterpriseType() == Enterprise.EnterpriseType.GoverningBody) {
                        for(Organization organization: enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if(organization instanceof DoctorOrganization){
                                for (UserAccount drUserAccount : organization.getUserAccountDirectory().getUserAccountList()) {
                                    DoctorAccount dr = (DoctorAccount) drUserAccount;
                                    if(dr.isLicense()) {
                                        Object row[] = new Object[2];
                                        row[0] = drUserAccount;
                                        row[1] = dr.isLicense();
                                        dtm.addRow(row);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGetPrescriptionActionPerformed

    private void managePrescriptionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePrescriptionsBtnActionPerformed
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new PrescriptionJPanel(userProcessContainer, userAccount, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePrescriptionsBtnActionPerformed

    private void viewRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestBtnActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            PrescriptionRequest prescriptionRequest = (PrescriptionRequest) workRequestJTable.getValueAt(selectedRow, 0);
            
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            userProcessContainer.add(new PrescriptionRequestJPanel(userProcessContainer, userAccount, system, prescriptionRequest));
            layout.next(userProcessContainer);
        } 
        else {
            JOptionPane.showMessageDialog(null, "Please select a request.");
        }
    }//GEN-LAST:event_viewRequestBtnActionPerformed
public void setColor(JButton p){
        p.setBackground(new Color(102,102,255));
    }
    public void resetColor(JButton p1){
        p1.setBackground(new Color(255,255,255));
        
    }
    private void refreshTestJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshTestJButtonMouseEntered
        // TODO add your handling code here:
        setColor(refreshTestJButton);
    }//GEN-LAST:event_refreshTestJButtonMouseEntered

    private void refreshTestJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshTestJButtonMouseExited
        // TODO add your handling code here:
        resetColor(refreshTestJButton);
    }//GEN-LAST:event_refreshTestJButtonMouseExited

    private void btnGetPrescriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetPrescriptionMouseEntered
        // TODO add your handling code here:
        setColor(btnGetPrescription);
    }//GEN-LAST:event_btnGetPrescriptionMouseEntered

    private void btnGetPrescriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetPrescriptionMouseExited
        // TODO add your handling code here:
        resetColor(btnGetPrescription);
    }//GEN-LAST:event_btnGetPrescriptionMouseExited

    private void viewRequestBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequestBtnMouseEntered
        // TODO add your handling code here:
        setColor(viewRequestBtn);
    }//GEN-LAST:event_viewRequestBtnMouseEntered

    private void viewRequestBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequestBtnMouseExited
        // TODO add your handling code here:
        resetColor(viewRequestBtn);
    }//GEN-LAST:event_viewRequestBtnMouseExited

    private void managePrescriptionsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePrescriptionsBtnMouseEntered
        // TODO add your handling code here:
        setColor(managePrescriptionsBtn);
    }//GEN-LAST:event_managePrescriptionsBtnMouseEntered

    private void managePrescriptionsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePrescriptionsBtnMouseExited
        // TODO add your handling code here:
        resetColor(managePrescriptionsBtn);
    }//GEN-LAST:event_managePrescriptionsBtnMouseExited
    
    private void populateStoreTable(){
        DefaultTableModel dtm = (DefaultTableModel) workRequestJTable.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()) {
            PrescriptionRequest prescriptionWorkRequest = (PrescriptionRequest) workRequest;
            if(prescriptionWorkRequest.getPrescription().getPatient() != null){
                if(prescriptionWorkRequest.getPrescription().getPatient().equals(userAccount)){
                    StoreAccount storeAccount = (StoreAccount) prescriptionWorkRequest.getStoreAccount();

                    String storeAddress = "";
                    if(storeAccount != null) {
                        storeAddress = storeAccount.getAddress();
                    }

                    Object row[] = new Object[4];
                    row[0] = prescriptionWorkRequest;
                    row[1] = storeAddress;
                    row[2] = prescriptionWorkRequest.getStatus();
                    row[3] = Helper.getCurrentDateTimeFromDateObject(prescriptionWorkRequest.getRequestDate());

                    dtm.addRow(row);  
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PatientName;
    private javax.swing.JButton btnGetPrescription;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JButton managePrescriptionsBtn;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JTable userWorkRequestJTable;
    private javax.swing.JLabel valueLabel1;
    private javax.swing.JButton viewRequestBtn;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

}
